export enum OrderEnum {
  ALL = 'ALL',
  PEDDING_PAY = 'PEDDING_PAY',
  PEDDING_DELIVERED = 'PEDDING_DELIVERED',
  PEDDING_RECEIVED = 'PEDDING_RECEIVED',
  PEDDING_COMMENT = 'PEDDING_COMMENT',
  AFTER_SERVICES = 'AFTER_SERVICES',
}
